[package]
name = "perfconv"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
description = "A tool for parsing Performai game levels"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
eyre = "0.6.12"
thiserror = "2.0.12"
